### ISSUE TITLE
TypeError: unsupported operand type(s) for -: 'IntVector' and 'int'

### ISSUE THREAD

**Issue by AlexanderAivazidis** [saketkc/pySCTransform#4]
Hi!

I have just installed pySCTransform and tried running through the tutorial and unfortunately got this error:

![image](https://user-images.githubusercontent.com/46488185/120937736-00f9c700-c707-11eb-985e-ffaf524e039a.png)

I got the same error when using my own data instead of the pbmc tutorial data.

I am using python 3.76. I have attached the whole tutorial notebook attempt, with a list of all package versions used. Would be great if you can help me with this!

[Untitled.pdf](https://github.com/saketkc/pySCTransform/files/6604792/Untitled.pdf)

Best wishes,

Alexander

**Comment by saketkc** [comment]
Hi @AlexanderAivazidis, I am in the  process of doing some clean ups and making a release. In the meanwhile, can you confirm if this error disappears if you install from a different branch: `pip install git+https://github.com/saketkc/pySCTransform.git@feat/fix_poisson`? See [colab notebook](https://github.com/saketkc/pySCTransform/blob/master/notebooks/pbmc3k_umap.ipynb) for an example.

**Comment by AlexanderAivazidis** [comment]
Hi @saketkc 
yes this error is still the same after reinstalling with pip install git+https://github.com/saketkc/pySCTransform.git@feat/fix_poisson
Ok I can wait and try the next release, thanks!
Best wishes,
Alexander

**Comment by saketkc** [comment]
Hi Alexander, while I haven't made a release yet, you can try installing the develop branch, that should fix the issue.

```
pip install git+https://github.com/saketkc/pySCTransform.git
```

Feel free to reopen, of course.
