### ISSUE TITLE
Is it possible to regress out cell cycle scores or other features?

### ISSUE THREAD

**Issue by liuzj039** [saketkc/pySCTransform#6]
* pySCTranscform version: 0.1.1
* Python version: 3.8
* Operating System: centOS 7

### Description

Many thanks to the developers for their willingness to port SCTransform to python.

I noticed that the `vst` argument contains `batch_var`, and that according to the original R version of sctransform, the argument `latent_var` should be able to contain some other factors that need to be regressed out.
However, these parameters are not included in the function SCTransform.
Even if we use the `vst` function directly, we have no way to pass the cell's meta information to vst.
After checking the source code I thought that concatenating this meta information directly with `cell_attr` might be a viable solution. just like this:
```
vst_out = pysctransform.vst(
    mtx.T,
    gene_names=adata.var_names.tolist(),
    cell_names=adata.obs_names.tolist(),
    latent_var=['log10_umi', 'S_score', 'G2M_score'],
    batch_var=None,
    method="theta_ml",
    cell_attr=df_cellAttr, # df_cellAttr contains cell score information, and will concatenate with cellAttr : `cell_attr = pd.concat([df_cellAttr, cell_attr], axis=1)`
    verbosity=1
)

```
From the source code, it seems that factors such as batch effects that need to be removed are included in the calculation when estimating theta values. But in terms of the final results, it doesn't seem to have worked.

After performing PCA on the above results I got this graph.
![image](https://user-images.githubusercontent.com/55271666/125614981-98991e20-64d0-4908-8f3f-95fd15cf2604.png)

I am very sorry if there is something that I missed.

**Comment by saketkc** [comment]
Hi @liuzj039, thanks for the question. Currently, `batch_var` support doesn't exist though I plan to add it soon. I should clarify this in the README.

**Comment by liuzj039** [comment]
Thank you for your quick reply. It looks like I still need to rely on rpy2 to use the R version for now. Looking forward to the next updates！
